name: 'check'

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/tflint.yml'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1

      - name: Check fmt
        id: fmt
        run: terraform fmt -check

      - name: Run tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: 'github-pr-review'

      - name: Init
        id: init
        run: terraform init

      - name: Validate
        id: validate
        run: terraform validate -no-color

